### ISSUE TITLE
character text files

### ISSUE THREAD

**Issue by wg481** [nitrodragon/GameStats#10]
What website/program saves the char files as txt's?

**Comment by EthanBar** [comment]
Woah hi there! This repository is not active, twas a fun project from high school with friends.
I don't believe we ever implemented any save states nor does anything write to a text file. Let me know if I can provide any other info or help.

**Comment by wg481** [comment]
The characters are all saved as text files. Leads me to think y'all used an online character generator. That's why I was asking.

So if it's not active I can fork it freely...

Yeah, Reagan said y'all ain't working on it anymore. I may ask him if I can start devving some stuff for him.

**Comment by EthanBar** [comment]
Ah right I see those now, @nitrodragon what tool did you use to create these characters files? And of course feel free to fork.

**Comment by SirNectarine** [comment]
@EthanBar I doubt he has access to GitHub since he's on his mission.

Gotta say it would be really cool to finally have some progress on this project, even if it's just a little 👀 I feel passionate about the story and characters I added, which might not all (if any lol) be included in this repository. @wg481 i could share those docs with you so you can know what we've got so far if Reagan's cool with it (which I'm sure he will be). I swore an oath to bring this project to completion even if it takes us 30 years, and I intend to keep that. 

Anyways, glad to see you guys, and to see some activity on this for the first time in a while. I've been missing it recently.

**Comment by wg481** [comment]
@SirNectarine Oh, hey Jared.
It's Van btw.
Anyways, I know it's late but I outlined everything in the fork about the characters. I made the fork so that Reagan can keep the original code of TSky.
Turns out those are HeroMachine 2.5 concepts. I'll ask Reagan for more info about them, like if he would want Roman to draw out real characters.
Frankly, him just generally being busy these last four years stopped development completely. I remember when he stopped talking about this project a few years back. I might as well (at least try to help) make it a reality.

**Comment by SirNectarine** [comment]
@wg481 Ah, hey there Van! Good to know you're on board too. Yeah, we all got pretty busy haha. Development totally stopped back then but it's still been in the back of our minds ever since (though I can't speak for Ethan). I'm sure you'll be able to contribute something useful!

**Comment by wg481** [comment]
@SirNectarine Hopefully. I mean, I got nowhere near the experience, but this project must go on!
I may end up starting a few pull requests on master just to update stuff.
